"""
Resemble AI deepfake detection provider (audio / video / image).
API: POST https://app.resemble.ai/api/v2/detect  (multipart file upload)
Uses synchronous mode via `Prefer: wait` header so we get the verdict inline.
Falls back to async (UUID poll via GET /api/v2/detect/{uuid}) if needed.
"""
import asyncio

import httpx

from app.config import settings

API_BASE = "https://app.resemble.ai/api/v2"
POLL_INTERVAL = 3
POLL_MAX = 60


class ResembleAIError(Exception):
    pass


def _headers() -> dict:
    return {"Authorization": f"Bearer {settings.RESEMBLE_AI_API_KEY}"}


def _normalize_audio(item: dict) -> dict:
    """Normalize a Resemble AI detect response item for audio to our standard format."""
    metrics = item.get("metrics") or {}
    label = (metrics.get("label") or "").lower()

    agg = metrics.get("aggregated_score")
    if agg is not None:
        score = float(agg) * 100
    else:
        scores = metrics.get("score") or []
        if scores:
            score = float(scores[0]) * 100
        else:
            score = 95.0 if label == "fake" else 5.0

    score = round(min(max(score, 0), 100), 1)

    findings = []
    if label == "fake":
        findings.append({
            "detail": f"Resemble AI verdict: FAKE — synthetic voice detected (aggregated confidence: {score:.0f}%)",
            "timestamp_or_location": None,
        })
        consistency = metrics.get("consistency")
        if consistency is not None:
            findings.append({
                "detail": f"Voice consistency score: {float(consistency) * 100:.0f}%",
                "timestamp_or_location": None,
            })
    elif label == "real":
        findings.append({
            "detail": f"Resemble AI verdict: REAL — authentic voice (score: {score:.0f}%)",
            "timestamp_or_location": None,
        })

    ast = item.get("audio_source_tracing")
    if ast and ast.get("label") and ast["label"] != "real":
        findings.append({
            "detail": f"Audio source tracing: likely generated by {ast['label']}",
            "timestamp_or_location": None,
        })

    return {
        "raw_score": score,
        "findings": findings,
        "vendor_label": label,
        "vendor_uuid": item.get("uuid"),
    }


def _normalize_video(item: dict) -> dict:
    """Normalize video detection (uses video_metrics + metrics for audio track)."""
    vm = item.get("video_metrics") or {}
    am = item.get("metrics") or {}

    v_label = (vm.get("label") or "").lower()
    a_label = (am.get("label") or "").lower()

    v_score_raw = vm.get("score")
    v_score = float(v_score_raw) * 100 if v_score_raw is not None else None
    a_agg = am.get("aggregated_score")
    a_score = float(a_agg) * 100 if a_agg is not None else None

    scores = [s for s in [v_score, a_score] if s is not None]
    score = round(max(scores), 1) if scores else (95.0 if "fake" in (v_label + a_label) else 5.0)

    findings = []
    if v_label == "fake":
        findings.append({"detail": f"Resemble AI visual verdict: FAKE (score: {v_score:.0f}%)" if v_score else "Resemble AI visual verdict: FAKE", "timestamp_or_location": None})
    if a_label == "fake":
        findings.append({"detail": f"Resemble AI audio track verdict: FAKE (score: {a_score:.0f}%)" if a_score else "Resemble AI audio track verdict: FAKE", "timestamp_or_location": None})
    if not findings:
        findings.append({"detail": f"Resemble AI verdict: {v_label or a_label or 'unknown'} (score: {score:.0f}%)", "timestamp_or_location": None})

    return {"raw_score": score, "findings": findings, "vendor_label": f"v:{v_label} a:{a_label}", "vendor_uuid": item.get("uuid")}


def _normalize_image(item: dict) -> dict:
    """Normalize image detection."""
    im = item.get("image_metrics") or {}
    label = (im.get("label") or "").lower()
    score_raw = im.get("score")
    score = round(float(score_raw) * 100, 1) if score_raw is not None else (95.0 if label == "fake" else 5.0)

    findings = []
    if label == "fake":
        findings.append({"detail": f"Resemble AI image verdict: FAKE (score: {score:.0f}%)", "timestamp_or_location": None})
    else:
        findings.append({"detail": f"Resemble AI image verdict: {label} (score: {score:.0f}%)", "timestamp_or_location": None})

    return {"raw_score": score, "findings": findings, "vendor_label": label, "vendor_uuid": item.get("uuid")}


async def _submit_and_get(filename: str, content: bytes) -> dict:
    """Upload file to Resemble Detect, wait synchronously, return the item dict."""
    async with httpx.AsyncClient(timeout=120.0) as client:
        resp = await client.post(
            f"{API_BASE}/detect",
            headers={**_headers(), "Prefer": "wait"},
            files={"file": (filename, content)},
            data={"audio_source_tracing": "true"},
        )
        if resp.status_code not in (200, 201):
            raise ResembleAIError(f"detect submit failed ({resp.status_code}): {resp.text[:300]}")

        body = resp.json()
        if not body.get("success"):
            raise ResembleAIError(f"detect returned success=false: {str(body)[:300]}")

        item = body.get("item", {})
        status = (item.get("status") or "").lower()

        # If sync wait returned immediately before completion, poll
        if status not in ("completed", "failed"):
            uuid = item.get("uuid")
            if not uuid:
                raise ResembleAIError("no uuid in detect response")
            for _ in range(POLL_MAX):
                await asyncio.sleep(POLL_INTERVAL)
                r = await client.get(f"{API_BASE}/detect/{uuid}", headers=_headers())
                if r.status_code == 200:
                    item = r.json().get("item", {})
                    if (item.get("status") or "").lower() in ("completed", "failed"):
                        break
            else:
                raise ResembleAIError(f"detect poll timed out for {uuid}")

        if (item.get("status") or "").lower() == "failed":
            raise ResembleAIError(f"detect job failed: {str(item)[:300]}")

        return item


async def analyze_audio(filename: str, content: bytes) -> dict:
    item = await _submit_and_get(filename, content)
    result = _normalize_audio(item)
    print(f"[DETECTION] resemble_ai audio: score={result['raw_score']} label={result.get('vendor_label')}")
    return result


async def analyze_video(filename: str, content: bytes) -> dict:
    item = await _submit_and_get(filename, content)
    result = _normalize_video(item)
    print(f"[DETECTION] resemble_ai video: score={result['raw_score']} label={result.get('vendor_label')}")
    return result


async def analyze_image(filename: str, content: bytes) -> dict:
    item = await _submit_and_get(filename, content)
    result = _normalize_image(item)
    print(f"[DETECTION] resemble_ai image: score={result['raw_score']} label={result.get('vendor_label')}")
    return result
